name: Norminette & Tests

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: python '3.x'

      - name: install Norminette
        run: 
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade norminette
      
      - name: Run norminette
        run: norminette *.c *.h
