name: Norminette & Tests

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install Norminette
        run: |
          python3 -m pip install --upgrade pip 
          python3 -m pip install norminette
      
      - name: Run norminette
        run: norminette ft_strlen.c libft.h
      
      - name: Run strlen tests
        run: |
          cc test_ft_strlen.c ft_strlen.c -o test_ft_strlen
          ./test_ft_strlen
      
      - name: Run isalpha tests
        run: |
          cc ft_isalpha.c test_ft_isalpha.c -o test_ft_isalpha
          ./test_ft_isalpha
